### ISSUE TITLE
[Feature Request] Packing WebApp as Android APK

### ISSUE THREAD

**Issue by RyanBram** [nwutils/Web2Executable#88]
Hi, Joey.

Thanks for creating a great application. It help me so much in my initial game project.
As I am also planning to supporting Android as well in my program, can you integrate [Crosswalkproject](https://crosswalk-project.org/) in your GUI for automating build process for Android. [Mr.Chay](http://www.mrchay.com/projects/HTML5toAPK) has created a simple commandline script for this task, but if it can also integrated in your GUI software, it will be a lot easier and really nice. Sorry for any inconvenience.

Regards,
Ryan

**Comment by jyapayne** [comment]
Hey Ryan,

You are most welcome! I'm glad it's helped you out :) 

I took a look at the crosswalk project you linked, and it unfortunately does not support Node.js. What this means is that the project cannot be successfully integrated due to the fact that Node.js functions would be available on the desktop version, and not the Android/mobile versions. In my quick look, I didn't see any way to read and write files to the Android memory card, which means that I would not even be able to write a wrapper to simulate some Node.js functionality.

I agree this is a cool idea, but I think it's best left for a separate application. If NW.js (or some other offering like it) starts supporting Android, it will be at the top of my priorities to bring it to Web2Executable. Until then, I'm afraid mobile support is not possible yet.

Cheers,
Joey

**Comment by CrandellWS** [comment]
Hope I am not off base here but I think [JXcore](http://jxcore.com/) could help:

https://github.com/jxcore/jxcore

They describe themselves as:

>JXcore can compile JavaScript sources into mobile application packages.
> 100% Node.JS Compatible
> JXcore is a Node.JS fork with additional features.

It may be more appropriate to request nw.js to integrate JXcore for mobile through webviews? idk

Any thoughts?

**Comment by CrandellWS** [comment]
See: https://github.com/nwjs/nw.js/issues/3113

**Comment by jyapayne** [comment]
You're correct about the NW.js integration, since JXCore does not provide any rendering and would require a Webkit front end. There isn't really a way I see that I can integrate it into Web2Exe.

I'll have to keep my eye on the issue you linked. It would be awesome if Roger integrated JXCore into NW.js!
